version: '3.9'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: atuser
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: animal_tracker

  animal-tracker-service:
    container_name: animal-tracker-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/animal_tracker
      - SPRING_DATASOURCE_USERNAME=atuser
      - SPRING_DATASOURCE_PASSWORD=Password123
    networks:
      - spring-postgres

volumes:
  db-data:
networks:
  spring-postgres:
