server:
  port: 8080
  servlet:
    contextPath: /animal-tracker-api
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      file-date-format: dd-MM-yyyy
      pattern: combined
      prefix: access
      rename-on-rotate: true
      rotate: true
      suffix: .log
    basedir: .

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/animal_tracker}
    username: ${SPRING_DATASOURCE_USERNAME:atuser}
    password: ${SPRING_DATASOURCE_PASSWORD:Password123}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/schema.xml
    enabled: true
