spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/animal-tracker}
    username: ${SPRING_DATASOURCE_USERNAME:atUser}
    password: ${SPRING_DATASOURCE_PASSWORD:Password123}
    driverClassName: org.postgresql.Driver

server:
  port: 8080
  servlet:
    contextPath: /animal-tracker-api
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      file-date-format: dd-MM-yyyy
      pattern: combined
      prefix: access
      rename-on-rotate: true
      rotate: true
      suffix: .log
    basedir: .
